### ISSUE TITLE
Read temperature from a config file

### ISSUE THREAD

**Issue by martin-schmidt** [Sepero/temp-throttle#10]
I would like to take the temperarure from a config file if no command line argument is given.

**Comment by Sepero** [comment]
Sorry I don't have time now to review this, but thank you for your submission. It is good and ambitious. I hope I may be able to review it in the coming weeks. Cheers

**Comment by martin-schmidt** [comment]
Just pushed some more changes to my forks master branch, see:   https://github.com/martin-schmidt/temp-throttle/commit/267a5ea3e479ca940db7d841ebfaade2f640c007

I added an init.d script to be able to run temp-throttle as a deamon. The commit also contains the config-file feature related to this issue.

**Comment by Sepero** [comment]
Hi Martin. I finally added in support for configuration file. Also added in files for init.d and systemd. You can find it all in the "testing" branch. If you could give it a test, I would greatly appreciate it. Best regards.  :)

**Comment by martin-schmidt** [comment]
Hey @Sepero,

fyi: I've seen this and will give it a test as soon I have a free time slot. Probably next week.

**Comment by muflone** [comment]
Hi

The configuration file parsing is really poor and unnecessary, just source the content of the configuration file inside the executable and you'll have the MAX_TEMP variable set.

Apart this, the systemd file should be updated in order to use the configuration file instead of asking the temperature from the service instance argument. Actually the required service instance entirely defeats the purpose of the configuration file, requiring an explicit temperature on the service launch.

**Comment by Sepero** [comment]
> the systemd file should be updated in order to use the configuration file instead of asking the temperature from the service instance argument.

Yes, I agree. You have to pardon my ignorance about how systemd works. Muflone, if you have the time, please submit to me a patch for the systemd file.

**Comment by Sepero** [comment]
> configuration file parsing is really poor and unnecessary

I'm sorry you feel that way, Muflone. Genuinely. I did several hours of research on the best way to implement that algorithm using standard gnu tools. If you could give any suggestions on improving it, then I would gladly welcome them.

> just source the content of the configuration file inside the executable and you'll have the MAX_TEMP variable set.

I have considered this, and yes I see how it would be the simpler route. However, I have also imagined different scenarios where a system administrator may wish to give temperature safety controls to an unprivileged user. By using a parser, the config file can safely be given ownership to a non-root user. Thus allowing a non-root user to be delegated temperature control, without fear of harming the system. I hope the choice I have made appears reasonable.

**Comment by muflone** [comment]
Maybe you didn't get my hint.

You can still use a separated configuration file but you don't need to write complex and unuseful functions to parse the content, just source the configuration file from the executable.
In one sentence: replace your complex parsing function with this single character: "." (which is an alias for the command "source")

See PR #20

**Comment by Sepero** [comment]
Hi Muflone. I'm sorry I didn't separate this out clearly from the first time. Please see Issue #21

**Comment by martin-schmidt** [comment]
> However, I have also imagined different scenarios where a system administrator may wish to give temperature safety controls to an unprivileged user.

Because this is a good point and maintaining code for the configutation two times in different ways is not an option, I changed my mind since  https://github.com/Sepero/temp-throttle/pull/12 and wouldn't add support for sourcing the file.

**Comment by muflone** [comment]
> However, I have also imagined different scenarios where a system administrator may wish to give temperature safety controls to an unprivileged user.

In this scenarios, it's better to avoid sourcing the configuration file (systemd on its own can parse configuration files), so please close my PR.
