### ISSUE TITLE
Add support for cpupower

### ISSUE THREAD

**Issue by muflone** [Sepero/temp-throttle#19]
Hi

please add the support for cpupower 

```
$ cpupower 
Usage:  cpupower [-d|--debug] [-c|--cpu cpulist ] <command> [<args>]
Supported commands are:
    frequency-info
    frequency-set
    idle-info
    idle-set
    set
    info
    monitor
    help

Not all commands can make use of the -c cpulist option.

Use 'cpupower help <command>' for getting help for above commands.
```

**Comment by Sepero** [comment]
Sorry for my ignorance. Is cpupower different from cpufreq-utils?

**Comment by muflone** [comment]
Yes, they're two different things.

cpufrequtils uses the commands cpufreq-set and cpufreq-info
http://manpages.ubuntu.com/manpages/utopic/man1/cpufreq-set.1.html

cpupower uses the command cpupower
http://manpages.ubuntu.com/manpages/utopic/man1/cpupower.1.html

**Comment by Sepero** [comment]
Very good. I will look into it further. :)
