### ISSUE TITLE
Systemd to not require input

### ISSUE THREAD

**Issue by Sepero** [Sepero/temp-throttle#21]
From Muflone on #10

> the systemd file should be updated in order to use the configuration file instead of asking the temperature from the service instance argument.

Yes, I agree. You have to pardon my ignorance about how systemd works. Muflone, if you have the time, please submit to me a patch for the systemd file.

**Comment by muflone** [comment]
Before this can be resolved, the configuration file must exist.
A service file cannot handle the MAX_TEMP by its own.

So before to fix this issue please provide a standard configuration file, actually it's at user option.

At the same time, please consider to avoid to add another file to /etc but instead put it into /etc/conf.d where multiple configuration files used by services live.

**Comment by Sepero** [comment]
Hi Muflone. I have a couple of issues I'm facing with changing the config dir. 1. Ubuntu LTS doesn't (yet?) have an `/etc/conf.d` dir, and 2. It appears that the dir also is not defined in the [Linux FHS](http://webcache.googleusercontent.com/search?q=cache:5zSkmjFS_2wJ:https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html+&cd=1&hl=en). Though if I can realize your proposal is the most reasonable action, then I still certainly will want to make this directory change.

The problem is that I'm having difficultly finding any information online about `/etc/conf.d`, why it exists, and the definition of what types of files it should contain. If we could gather some links regarding the stated information, then we may have very good reason to implement the change.

**Comment by muflone** [comment]
Unfortunately the /etc settings hierarchy is mostly distro dependant.
On Debian family the settings are usually stored under /etc/default while Arch Linux and Gentoo prefer /etc/conf.d, choose that one that you prefer.

**Comment by Sepero** [comment]
Yes, I can see this issue here. I'd be willing to create both directories and have the file available in both, but I'm not 100% sure how I would do that. Symlinks? What issues might that incurr?

**Comment by muflone** [comment]
There's no reason to have the file twice, choose that one that you prefer.
It's duty of the distro maintainer to place the files where they have to work in the distribution.
Don't mix the developer duties with the maintainer duties.

**Comment by Sepero** [comment]
I see. And apparently Fedora chooses to also use `/etc/sysconfig`, and Slackware uses `rc.d`. I am leaning a little in favor of the Debian structure because of prominently available information. What I mean is, when I Google search for "/etc/default", then I can easily find multiple answers about it's purpose. Like this http://askubuntu.com/questions/429592/what-is-the-purpose-of-etc-default

If there are any reasons you think I should choose another directory structure, then just let me know.

**Comment by Sepero** [comment]
I have been thinking about- and researching this a lot, over the past 48 hours. The different directories init, rc.d, sysconfig, default, conf.d... To me, all of these appear to be some kind of political game. A game that I don't wish to be a part of. If and when the FHS comes out with a defined _initialization directory_, then I would be happy to place the configuration file there. Until then, I currently feel like it's unnecessary. I think I would  prefer to follow in the footsteps of `apparmor`, `samba`, and `vsftp`, because they all appear to just put the config file directly in `/etc/`
