### ISSUE TITLE
Support intel_powerclamp driver

### ISSUE THREAD

**Issue by flyser** [Sepero/temp-throttle#26]
Please support throttling with the intel powerclamp driver, which should (in theory) allow better performance than cpu frequency scaling.
See https://www.kernel.org/doc/Documentation/thermal/intel_powerclamp.txt for details.

**Comment by Sepero** [comment]
Please allow me time and I will try to look into this more. Thank you for the suggestion. :)

**Comment by Sepero** [comment]
I apologize, but 1) temp-throttle wasn't designed to handle special architectures, and 2) I think I'm too stupid to implement this.

If someone would like to fork my work, for the purpose of adding this special support, I would be happy to give any advice I can to help get it running. Again, I apologize for any inconvenience.
