### ISSUE TITLE
Thermal throttling?

### ISSUE THREAD

**Issue by piegamesde** [Sepero/temp-throttle#33]
There is this nice script that does thermal throttling: https://github.com/Sepero/temp-throttle/

It's just a loop polling the temperature and changing the max frequency until that temperature is below a threshold.

I think it would be a nice addition to have such features and not that hard to implement. (Since it is using another interface than this extension, it might be faster to re-implement it from scratch)

**Comment by piegamesde** [comment]
Oops this is not the right repository :man_facepalming: Sorry for the spam.

**Comment by Sepero** [comment]
Hi piegamesde. If you're using the code in another project, then I'd love to hear the details. Thanks for your interest. :)

**Comment by piegamesde** [comment]
I'd like to have this in https://github.com/martin31821/cpupower/issues/62, but so far I hadn't any time to do this nor did anyone else implement it.
