### ISSUE TITLE
Allow specifying TEMPERATURE_FILES path in the config file

### ISSUE THREAD

**Issue by terencode** [Sepero/temp-throttle#36]
I don't know how much standardized the path to get the temperature is, but I needed to add `/sys/class/hwmon/hwmon3/temp1_input` to the TEMPERATURE_FILES in `/sbin/temp-throttle` for my fx9370 with it8721.

**Comment by Sepero** [comment]
Adding new paths is very easy. Thanks for your submission. It will eventually be included as a default location.
