### ISSUE TITLE
It just keeps throttling down, but it does not reduce the the temps 

### ISSUE THREAD

**Issue by QazCetelic** [Sepero/temp-throttle#38]
I'm doubting that it actually reduces the clockspeeds, and that it therefore does not reduce temps

When running `sudo bash temp_throttle.sh 75`
```
Initialize to max CPU frequency
unthrottle 4100000
throttle 4000000
throttle 3900000
throttle 3800000
throttle 3700000
throttle 3600000
throttle 3500000
throttle 3400000
throttle 3300000
throttle 3200000
```
And it keeps going down and down while the temps stay at ~75, it might be the case that 4.1Ghz is way too high but that doesn't explain that it starts of at 75 degrees at 4.1Ghz and goes down to 3.2Ghz without changing the temperature

**Comment by Jeremy7701** [comment]
Assuming you are running a slightly modified **temp_throttle.sh**,
**#Set the first argument as the maximum desired temperature.**
So you have requested maximum performance, whilst not exceeding 75 degrees.
Suggest running at 3.2GHz (in this situation) is required.
Don't know about you, but my CPU only has 5 discrete speeds
3800000 3400000 2600000 1800000 1400000

**Comment by Sepero** [comment]
QazCetelic
From the output you listed, the program appears to be operating correctly.

If you are measuring your temperature at 75C, and it doesn't change at all, then I suspect you are measuring the temperature of something other than the CPU.

The CPU temperature will constantly be fluctuating in any system depending upon the load put on it. When idle, a CPU will be cooler.

Thank you for your feedback.
