### ISSUE TITLE
Was throttling down, now not working

### ISSUE THREAD

**Issue by jave808** [Sepero/temp-throttle#39]
See output below:
```
jave@ryzen7:~/bin$ sudo bash temp_throttle.sh 75
Author: Sepero 2016 (sepero 111 @ gmx . com)
URL: http://github.com/Sepero/temp-throttle/

Number of CPU cores detected: 16


Error: Could not determine available cpu frequencies

```
I've set my CPU control to Auto in BIOS. Something isn't right with the cpufreq command...

**Comment by Jeremy7701** [comment]
This means that `/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies` is empty or non-existent.

**Comment by Sepero** [comment]
Thank you, Jeremy. I don't check my messages often enough, and I could do for someone to take over this project

If the script was working on your system previously, but now is not working, you may also want to check out the Testing branch. You may have been using that before

**Comment by Jeremy7701** [comment]
> Thank you, Jeremy. I don't check my messages often enough, and I could do for someone to take over this project
> 
From my point of view, `temp_throttle` reached stability some time ago - I load it at boot time and just let it run all day.

Previously, where one program was known to be a CPU hog, I ran a script which would suspend/resume this one program according to temperature - but in a much inferior way to `temp_throttle`:-
`killall -s STOP "$PGM"`    # Pauses all processes matching "$PGM"
`killall -s CONT "$PGM"`    # Resumes all processes matching "$PGM"
A few programs don't like to be suspended/resumed, but most are OK with it.

**Comment by Sepero** [comment]
If this issue still exists, then please reopen the issue.
