### ISSUE TITLE
After Ctrl-C the CPU stays at low frequency

### ISSUE THREAD

**Issue by jbrepogmailcom** [Sepero/temp-throttle#41]
temp-throttle reduced my CPU to 10% and it stayed slow after I quit the script. How do I revert CPU to original throttling? I could enter temp-throttle 100, but I really do not know what is the maximum allowed temperature, so it could break my PC.

**Comment by Jeremy7701** [comment]
`temp-throttle 10` would allow anything to run at full speed - until your CPU reached 10 degrees!
Then it would do its best to progressively reduce your CPU frequency until the temperature dropped below 10 degrees - which would never happen.

Try `temp-throttle 70` as a conservative value. Laptops can use a higher value.

**Comment by Sepero** [comment]
The script will never increase the temperature of your CPU. If your PC is idling at 40C, then running `temp-throttle 100` will not change that, it will remain at 40C.

Running `temp-throttle 100` would only release all throttling.

**Comment by jbrepogmailcom** [comment]
I did not mean that temp-throttle would take 100%. I mean that if I run `temp-throttle 100`, then other apps would be allowed to use CPU until it reaches 100° and it would harm the PC. Also when I Ctrl-C temp-throttle that has been set to 45°, then CPU remains throttled, right? How do I make it jump back to BIOS power-optimized throttling?

**Comment by Jeremy7701** [comment]
Close down power hungry applications.
Leave temp-throttle to do its thing and it will unthrottle your CPU - note that 45°C is a very low temperature for CPU's.
45 is too low, 100 is too high, choose something in between.

**Comment by Sepero** [comment]
`temp-throttle` does not disable BIOS power-optimized throttling. So when you re-run with `temp-throttle 100`, then your system will run as if nothing has changed.

**Comment by Sepero** [comment]
New testing release branch code will completely unthrottle your CPU when it quits.
