### ISSUE TITLE
CPU never unthrottle if it never reaches temp less than set temperature minus 5°C

### ISSUE THREAD

**Issue by jbrepogmailcom** [Sepero/temp-throttle#42]
Hello. I usually set CPU temperature with temp-throttle very low in order to not to start the fan. Its OK for me to wait sometimes. Let's say I set temp to 45, which is prety usual when CPU is idle, but CPU very rarely reaches 40°C or less. I noticed that unthrottle is triggered only if CPU reaches less than throttle-temp minus 5°C. This means that if CPU never goes to 5°C less than set temp, it will never unthrottle.

There should be some warning that temp-throttle should NEVER be set less than to minimum running achievable CPU temperature plus 5°C.

I had to manually remove the "-5" in the script and now I am satisfied.

**Comment by Sepero** [comment]
The reason the 5 degree difference exists is as a cushion, to prevent it from constantly changing the CPU unreasonably.

Let us take an example. Without the cushion, let us imagine you set 45 as the max temp. Well at 46, it will throttle down. Then it will hit 45, it will **immediately** throttle back up again. Resulting in a loop of up/down/up/down...

With the cushion, it will throttle down to 45 and stop. It won't throttle more as long as the temperature is under (but near) 45. Then when the system starts to cool down to 40 or less, this will indicate that the system is no longer under processing load, and it is safe to throttle back up.

**Comment by Sepero** [comment]
All that being said, I'm pleased that you're able to modify it to your needs. This exactly why I wrote temp-throttle in bash and not some programming language. So normal people like ourselves can easily edit it to our desires. Cheers
