### ISSUE TITLE
Disable or Isolate CPU core to reduce temp

### ISSUE THREAD

**Issue by latot** [Sepero/temp-throttle#43]
Hi hi, I was doing some tests in a server, and I notice even with the actual method, is not possible to always keep the temp we want.

So, after collect data I notice the temp is also proportional to the number of cores we are using, so, I think would be great use CPU affinity to just lock a CPU core, and with that we can reduce the temp too.

I'm curios what would be the combination of cores enabled/frequency to get the best performance.

Thx.

**Comment by latot** [comment]
I found 2 ways to do this, one is:

```
echo 0 > /sys/devices/system/cpu/cpu3/online
```
This method have some... things:
https://stackoverflow.com/questions/44907731/programmatically-disable-cpu-core

The other one:
```
cset shield --cpu 4
```
https://github.com/lpechacek/cpuset
This project is old, and need a doc to explain how to run it..., is not as simple as run it.

**Comment by Sepero** [comment]
Thank you for your contribution. I will look into it. 👍🏻

**Comment by Sepero** [comment]
I will see about adding a cpu selection option to the next release.

**Comment by gustrd** [comment]
@Sepero, another idea that I think is good and that I'm using is disabling Intel's Turbo Boost before the first throttle down. It's responsible for a great part of the CPU's heat.

According to "https://github.com/georgewhewell/undervolt/blob/master/undervolt.py" it can be done with a simple:

`with open("/sys/devices/system/cpu/intel_pstate/no_turbo","w+") as file:
            file.write(str(intelTurboState))`
