### ISSUE TITLE
Some weird messages

### ISSUE THREAD

**Issue by darrepac** [Sepero/temp-throttle#44]
Hi

This script is very nicely working avoid to have a server reaching dangerous temp.
Just wanted to inform you that even if it is working, I got the following some times:

```
line 148: [: -gt: unary operator expected
line 150: [: -le: unary operator expected
```

**Comment by Sepero** [comment]
Sometimes?

That's a very curious error to get only sometimes. Perhaps you can elaborate on "sometimes". Does it occur most when first starting the script? Is it possible you have modified the code in anyway?

**Comment by darrepac** [comment]
I agree!
I said « sometimes » because I saw it in the console 1 time (near the launch of the script)

**Comment by Sepero** [comment]
With an error like that, I suspect your CPU is being fully throttled at boot, and remaining that way, regardless of temperature. This shouldn't happen with bash as I understand. What version of bash do you have on your system?

**Comment by darrepac** [comment]
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)

**Comment by Sepero** [comment]
Thank you for the report. I'll have to look into it further

**Comment by Sepero** [comment]
Too old. Unknown problem. If still having this problem, then please reopen the issue.
