### ISSUE TITLE
Error: Unable to determine available CPU Frequencies

### ISSUE THREAD

**Issue by bfenty** [Sepero/temp-throttle#48]
I'm receiving an error about not being able to determine CPU frequencies. This is on a Dell Poweredge 710. I'm assuming there's something odd about the Dell system that's keeping this from working, and I don't know enough about it to make a change.

Can you help me figure out what I need to do to allow this to happen? Thank you.

**Comment by Sepero** [comment]
I think this has been fixed. When the available frequencies file is not found, in between frequencies will be auto generated. If this is not fixed, please reopen the issue.
