### ISSUE TITLE
Line 82: echo: write error: Invalid argument

### ISSUE THREAD

**Issue by t4exanadu** [Sepero/temp-throttle#5]
When I run temp_throttle.sh with root privileges, the following error is displayed in the shell terminal:
![image](https://cloud.githubusercontent.com/assets/3803896/2810212/81669612-cda8-11e3-9445-695e29f78c9d.png)

Lines 80 - 83 are:
	echo $FREQ_TO_SET
	for i in $(seq 0 $CORES); do
		echo $FREQ_TO_SET > /sys/devices/system/cpu/cpu$i/cpufreq/scaling_max_freq
	done

I'm wondering will this error affect the function of the script? It seems to be working OK, my laptop isn't going above 60c, which is the desired threshold.

I am running Peppermint Linux 3. If you need any other info, let me know!

**Comment by zlayaptichka** [comment]
Hello. It seems OS not allowing directly writing to these files.
I created a pull request that fixing this error: https://github.com/Sepero/temp-throttle/pull/8

**Comment by Sepero** [comment]
Hi zlay. I have reviewed your changes. I am not able to apply them as they are currently, because they introduce the dependency for the package "cpufrequtils". I think I will attempt to apply the changes similar to this logic:

    try (echo $FREQ_TO_SET > max_freq)
        on fail try (cpufreq-set -c $i --max $FREQ_TO_SET)
            on fail try (echo suggestion to user to try installing cpufrequtils)


Thank you for your submission. :)

**Comment by zlayaptichka** [comment]
You're welcome.
Please close this pull request (https://github.com/Sepero/temp-throttle/pull/8), i can't find how to close pull request created by yourself.
Thanks.

**Comment by zlayaptichka** [comment]
And this is the logic: https://github.com/zlayaptichka/temp-throttle/commit/7f5896e549d0f5dc10cf32a8cec940319f99f54c

**Comment by zlayaptichka** [comment]
You're welcome.
Here's the pull request which adding fallback to cpufrequtils: #9

**Comment by Sepero** [comment]
I'm going to close this issue for now. It may be reopened if anyone writes in with future issues concerning this.
