### ISSUE TITLE
Set minimum allowed frequency.

### ISSUE THREAD

**Issue by XeromX** [Sepero/temp-throttle#53]
I would like to set minimum frequency 1.7 Ghz regardless of temperature, currently it can go down to 400mhz which is making computer too slow. My goal is to have a silent computer and prevent fan from turning on so I set max temp 53 degrees. 
Would you be so kind and to give some more settings to users in which it is going to be possible to set minimum allowed frequency?

**Comment by Sepero** [comment]
This is possible with a single edit to the script. See issue #54
