### ISSUE TITLE
Current CPU temperature file detection is inaccurate

### ISSUE THREAD

**Issue by Vdragon** [Sepero/temp-throttle#7]
Currently temp-throttle uses the first found file in TEMPERATURE_FILES as CPU temperature, however it is pretty inaccurate as:
- temperature is not always CPU temperature(Motherboard etc.)
- CPU temperature is not always the most accurate one(per-core temperature)
- temperature file of the first CPU is not always starts from 1(don't know why)

Maybe we should put files that are known to be CPU temperature over generic ones(like from specific hardware monitor driver).

**Comment by Djfe** [comment]
Just found this script: amazing!
thx for writing it

what I found out:
for me cpu temperatures are located in /sys/class/hwmon/hwmon0/
hwmon0 is the only one that exists for me
I'm using Fedora 21/22

The CPU temperatures are in temp2, temp3,temp4 and temp5 (4 cores)
temp1 doesn't exist (I have no clue why)

you can find out what it is if you output name first of all (/sys/class/hwmon/hwmon0/name)
it contains "coretemp" for me
tempx_label outputs "Core x" for me
x is a number here
it's temp_2-5 and Core 0-3 for me

maybe labels allow a correct detection of the cpu temperatures
but there is probably a better way
it probably should also decide depending on the used OS

**Comment by Sepero** [comment]
Thanks for the report, Djfe. Please tell me this info about the hardware you are running:
- Computer Manufacturer
- CPU
- Architecture

Also what is:
- Your kernel version: uname -a
- The exact location of for reading the temperature of your first CPU core ("/sys/class/hwmon/hwmon0/hwmon0/temp2 ?")

**Comment by Djfe** [comment]
Yes it's temp2 like for @vdragon it doesn't start from 1
My notebook:
http://www.toshiba.de/discontinued-products/satellite-a660-11m/

I'll post the kernel later
And I'll zip the hwmon for you, so you can take a look yourself ;)

**Comment by Sepero** [comment]
This appears to be what I have so far  :)
- Toshiba
- Intel i7
- 64bit
- Linux bau.nb 4.1.12-101.fc21.x86_64 #1 SMP
- /sys/class/hwmon/hwmon0/hwmon0/temp2

**Comment by Sepero** [comment]
Additional question- Are there ever times when the temperature switches to the file `/sys/class/hwmon/hwmon0/hwmon0/temp1` or `/sys/class/hwmon/hwmon0/hwmon0/temp0`?

**Comment by Sepero** [comment]
Note: Support for `/sys/class/hwmon/hwmon0/hwmon0/temp2` has been added to the "testing" branch.

**Comment by Djfe** [comment]
ups it's only once hwmon0 not twice
/sys/class/hwmon/hwmon0/

the content:
http://www.file-upload.net/download-11039390/hwmon0.zip.html
(I didn't add the symlinks device and subsystem, because they contain symlinks back to hwmon0 and they are not important)

The notebook specs are correct
and yes I never noticed being core 0 something else than temp2

**Comment by Djfe** [comment]
totally forgot:
Linux bau.nb 4.1.12-101.fc21.x86_64 #1 SMP Wed Oct 28 15:18:44 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Sepero** [comment]
> ups it's only once hwmon0 not twice

Ok, I corrected for this in the testing branch

**Comment by Sepero** [comment]
Until someone can discover a better method for discovering CPU temperatures, I think that takes care of everything for now.

**Comment by findepi** [comment]
Just to add. In my case `/sys/class/hwmon/hwmon0/` contains a bunch of ACPI temperatures with `/sys/class/hwmon/hwmon0/temp8_input` being close to what I believe is CPU temperature as reported by `sensors` command. But, the CPU temperatures are in `/sys/class/hwmon/hwmon1/temp[24]_input` in my case (dual core i7). Oh,`cat /sys/class/hwmon/hwmon1/name` says "coretemp" while `cat /sys/class/hwmon/hwmon0/name` says "acpitz". Maybe this can be used to differentiate?

It seems, ability to specify custom temperature file may be handy (as in pull request #25). So may be ability to watch in many temperatures at once (like all cores.)

**Comment by Sepero** [comment]
My apologies for the long delay, findepi. I'm currently working on including that ability to specify a custom temperature location. You'll find it in the testing branch.

**Comment by Sepero** [comment]
Resolved in testing branch
